# Generated by Django 4.0.6 on 2022-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=150, verbose_name='username'),
        ),
    ]
