# Generated by Django 4.0.6 on 2022-07-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('dr', 'draft'), ('pu', 'published'), ('de', 'deleted')], default='dr', max_length=2),
        ),
    ]
