# Generated by Django 4.0.6 on 2022-12-01 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('dr', 'Draft'), ('pub', 'Published'), ('del', 'Deleted')], default='dr', max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.creator')),
            ],
            options={
                'permissions': [('can_edit_content', ' can edit content and title'), ('can_edit_meta', 'can edit slug, status and publish date')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('dr', 'Draft'), ('pub', 'Published'), ('del', 'Deleted')], default='dr', max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.creator')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.post')),
            ],
            options={
                'permissions': [('can_edit_content', ' can edit content and title'), ('can_edit_meta', 'can edit slug, status and publish date')],
            },
        ),
    ]
