# Generated by Django 4.0.6 on 2022-12-01 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 13, 17, 13, 792632)),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 13, 17, 13, 793493)),
        ),
    ]
