# Generated by Django 4.0.6 on 2022-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_post_published_at_alter_review_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
