# Generated by Django 4.0.6 on 2022-12-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_post_published_at_alter_review_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
