# Generated by Django 4.0.6 on 2022-12-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_post_options_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_edit_content', 'can edit content and title'), ('can_edit_meta', 'can edit slug, status and publish date')]},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_edit_content', 'can edit content and title'), ('can_edit_meta', 'can edit slug, status and publish date')]},
        ),
    ]
