# Generated by Django 4.0.6 on 2022-12-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_post_options_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
