# Generated by Django 4.0.6 on 2022-12-04 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
